'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.42
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------
'
' 2023-01-10	PV		Net7
' 2023-11-18	PV		Net8
' 2024-11-15	PV		Net9

Option Strict Off
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.42.
'

'''<remarks/>
<GeneratedCode("xsd", "2.0.50727.42"),
 Serializable(),
 DebuggerStepThrough(),
 DesignerCategory("code"),
 XmlType(AnonymousType:=True),
 XmlRoot([Namespace]:="http://tempuri.org/XMLSchema.xsd", IsNullable:=False)>
Partial Public Class Project

    Private targetField As TargetType

    Private importField As ImportType

    Private defaultTargetsField As String

    Private initialTargetsField As String

    '''<remarks/>
    Public Property Target() As TargetType
        Get
            Return Me.targetField
        End Get
        Set
            Me.targetField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Import() As ImportType
        Get
            Return Me.importField
        End Get
        Set
            Me.importField = Value
        End Set
    End Property

    '''<remarks/>
    <XmlAttribute()>
    Public Property DefaultTargets() As String
        Get
            Return Me.defaultTargetsField
        End Get
        Set
            Me.defaultTargetsField = Value
        End Set
    End Property

    '''<remarks/>
    <XmlAttribute()>
    Public Property InitialTargets() As String
        Get
            Return Me.initialTargetsField
        End Get
        Set
            Me.initialTargetsField = Value
        End Set
    End Property
End Class

'''<remarks/>
<GeneratedCode("xsd", "2.0.50727.42"),
 Serializable(),
 DebuggerStepThrough(),
 DesignerCategory("code"),
 XmlType([Namespace]:="http://tempuri.org/XMLSchema.xsd")>
Partial Public Class TargetType

    Private itemsField() As TaskType

    Private nameField As String

    '''<remarks/>
    <XmlElement("Message", GetType(TargetTypeTaskMessage)),
     XmlElement("MkDir", GetType(TargetTypeTaskMkDir))>
    Public Property Items() As TaskType()
        Get
            Return Me.itemsField
        End Get
        Set
            Me.itemsField = Value
        End Set
    End Property

    '''<remarks/>
    <XmlAttribute()>
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property
End Class

'''<remarks/>
<GeneratedCode("xsd", "2.0.50727.42"),
 Serializable(),
 DebuggerStepThrough(),
 DesignerCategory("code"),
 XmlType([Namespace]:="http://tempuri.org/XMLSchema.xsd")>
Partial Public Class ImportType

    Private nameField As String

    '''<remarks/>
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property
End Class

'''<remarks/>
<GeneratedCode("xsd", "2.0.50727.42"),
 Serializable(),
 DebuggerStepThrough(),
 DesignerCategory("code"),
 XmlType([Namespace]:="http://tempuri.org/XMLSchema.xsd")>
Partial Public Class TaskType

    Private outputField() As TaskTypeOutput

    Private conditionField As String

    '''<remarks/>
    <XmlElement("Output")>
    Public Property Output() As TaskTypeOutput()
        Get
            Return Me.outputField
        End Get
        Set
            Me.outputField = Value
        End Set
    End Property

    '''<remarks/>
    <XmlAttribute()>
    Public Property Condition() As String
        Get
            Return Me.conditionField
        End Get
        Set
            Me.conditionField = Value
        End Set
    End Property
End Class

'''<remarks/>
<GeneratedCode("xsd", "2.0.50727.42"),
 Serializable(),
 DebuggerStepThrough(),
 DesignerCategory("code"),
 XmlType(AnonymousType:=True)>
Partial Public Class TaskTypeOutput

    Private taskParameterField As String

    Private itemNameField As String

    Private propertyNameField As String

    Private conditionField As String

    '''<remarks/>
    <XmlAttribute()>
    Public Property TaskParameter() As String
        Get
            Return Me.taskParameterField
        End Get
        Set
            Me.taskParameterField = Value
        End Set
    End Property

    '''<remarks/>
    <XmlAttribute()>
    Public Property ItemName() As String
        Get
            Return Me.itemNameField
        End Get
        Set
            Me.itemNameField = Value
        End Set
    End Property

    '''<remarks/>
    <XmlAttribute()>
    Public Property PropertyName() As String
        Get
            Return Me.propertyNameField
        End Get
        Set
            Me.propertyNameField = Value
        End Set
    End Property

    '''<remarks/>
    <XmlAttribute()>
    Public Property Condition() As String
        Get
            Return Me.conditionField
        End Get
        Set
            Me.conditionField = Value
        End Set
    End Property
End Class

'''<remarks/>
<GeneratedCode("xsd", "2.0.50727.42"),
 Serializable(),
 DebuggerStepThrough(),
 DesignerCategory("code"),
 XmlType(AnonymousType:=True),
 XmlRoot("Message", [Namespace]:="http://tempuri.org/XMLSchema.xsd", IsNullable:=False)>
Partial Public Class TargetTypeTaskMessage
    Inherits TaskType

    Private importanceField As String

    Private textField As String

    '''<remarks/>
    <XmlAttribute()>
    Public Property Importance() As String
        Get
            Return Me.importanceField
        End Get
        Set
            Me.importanceField = Value
        End Set
    End Property

    '''<remarks/>
    <XmlAttribute()>
    Public Property Text() As String
        Get
            Return Me.textField
        End Get
        Set
            Me.textField = Value
        End Set
    End Property
End Class

'''<remarks/>
<GeneratedCode("xsd", "2.0.50727.42"),
 Serializable(),
 DebuggerStepThrough(),
 DesignerCategory("code"),
 XmlType(AnonymousType:=True),
 XmlRoot("MkDir", [Namespace]:="http://tempuri.org/XMLSchema.xsd", IsNullable:=False)>
Partial Public Class TargetTypeTaskMkDir
    Inherits TaskType

    Private directoriesField As String

    '''<remarks/>
    <XmlAttribute()>
    Public Property Directories() As String
        Get
            Return Me.directoriesField
        End Get
        Set
            Me.directoriesField = Value
        End Set
    End Property
End Class

