using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CS422
{
    class Program
    {
        static void Main(string[] args)
        {
            var sc = new SomeClass();

            Func<int, int> del = sc.getDelegate();
            int i1 = del(10);
            int i2 = del(3);
            Console.WriteLine(i1);
            Console.WriteLine(i2);

            Func<int, int> del2 = sc.getDelegate2();
            int j1 = del2(10);
            int j2 = del2(3);
            Console.WriteLine(j1);
            Console.WriteLine(j2);

            Console.ReadLine();
        }
    }

    class SomeClass
    {
        private int offset = 2;

        // test of a closure accessing instance local variable and instance class variable
        public Func<int, int> getDelegate()
        {
            int sum = 0;
            return delegate (int x)
            {
                sum += x;
                return sum + offset;
            };
        }



        // Here is closure generated by compiler (symbols renamed):
        private sealed class DisplayClass1
        {
            // Fields
            public SomeClass __this;
            public int sum;

            // Methods
            public int getDelegate__0(int x)
            {
                this.sum += x;
                return (this.sum + this.__this.offset);
            }
        }

        public Func<int, int> getDelegate2()
        {
            DisplayClass1 locals2;
            locals2 = new DisplayClass1();
            locals2.__this = this;
            locals2.sum = 0;
            return (Func<int, int>)locals2.getDelegate__0;
        }
    }
}
