'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.Configuration
Imports System.Runtime.CompilerServices


<CompilerGenerated(),
 GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")>
Partial Friend NotInheritable Class MySettings
    Inherits ApplicationSettingsBase

    Private Shared defaultInstance As MySettings = CType(Synchronized(New MySettings()), MySettings)

    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            Return defaultInstance
        End Get
    End Property

    <ApplicationScopedSetting(),
     DebuggerNonUserCode(),
     DefaultSettingValue("This is Setting1 string (Application)")>
    Public ReadOnly Property Setting1() As String
        Get
            Return CType(Me("Setting1"), String)
        End Get
    End Property

    <UserScopedSetting(),
     DebuggerNonUserCode(),
     DefaultSettingValue("This is Setting2 string (User)")>
    Public Property Setting2() As String
        Get
            Return CType(Me("Setting2"), String)
        End Get
        Set
            Me("Setting2") = Value
        End Set
    End Property

    <ApplicationScopedSetting(),
     DebuggerNonUserCode(),
     DefaultSettingValue("True")>
    Public ReadOnly Property SettingB() As Boolean
        Get
            Return CType(Me("SettingB"),Boolean)
        End Get
    End Property
End Class
