'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")>
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase

    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            Return defaultInstance
        End Get
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Configuration.DefaultSettingValueAttribute("This is Setting1 string (Application)")>
    Public ReadOnly Property Setting1() As String
        Get
            Return CType(Me("Setting1"), String)
        End Get
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Configuration.DefaultSettingValueAttribute("This is Setting2 string (User)")>
    Public Property Setting2() As String
        Get
            Return CType(Me("Setting2"), String)
        End Get
        Set
            Me("Setting2") = Value
        End Set
    End Property

    <Global.System.Configuration.ApplicationScopedSettingAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Configuration.DefaultSettingValueAttribute("True")>
    Public ReadOnly Property SettingB() As Boolean
        Get
            Return CType(Me("SettingB"), Boolean)
        End Get
    End Property
End Class
