'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.Configuration
Imports System.Runtime.CompilerServices


<CompilerGenerated(),
 GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")>
Partial Friend NotInheritable Class MySettings
    Inherits ApplicationSettingsBase

    Private Shared defaultInstance As MySettings = CType(Synchronized(New MySettings()), MySettings)

    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            Return defaultInstance
        End Get
    End Property
End Class
