'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.ComponentModel.Design
Imports System.Configuration
Imports System.Runtime.CompilerServices

Namespace My

    <CompilerGenerated(),
     GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0"),
     EditorBrowsable(EditorBrowsableState.Advanced)>
    Partial Friend NotInheritable Class MySettings
        Inherits ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
        Private Shared addedHandler As Boolean

        Private Shared addedHandlerLockObject As New Object

        <DebuggerNonUserCode(), EditorBrowsable(EditorBrowsableState.Advanced)>
        Private Shared Sub AutoSaveSettings(sender As Object, e As EventArgs)
            If Application.SaveMySettingsOnExit Then
                Settings.Save()
            End If
        End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
                If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Folder() As String
            Get
                Return CType(Me("Folder"), String)
            End Get
            Set
                Me("Folder") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Title() As String
            Get
                Return CType(Me("Title"), String)
            End Get
            Set
                Me("Title") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Subject() As String
            Get
                Return CType(Me("Subject"), String)
            End Get
            Set
                Me("Subject") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Author() As String
            Get
                Return CType(Me("Author"), String)
            End Get
            Set
                Me("Author") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Manager() As String
            Get
                Return CType(Me("Manager"), String)
            End Get
            Set
                Me("Manager") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Company() As String
            Get
                Return CType(Me("Company"), String)
            End Get
            Set
                Me("Company") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Category() As String
            Get
                Return CType(Me("Category"), String)
            End Get
            Set
                Me("Category") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Keywords() As String
            Get
                Return CType(Me("Keywords"), String)
            End Get
            Set
                Me("Keywords") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property Comments() As String
            Get
                Return CType(Me("Comments"), String)
            End Get
            Set
                Me("Comments") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode(),
         DefaultSettingValue("")>
        Public Property HyperlinkBase() As String
            Get
                Return CType(Me("HyperlinkBase"), String)
            End Get
            Set
                Me("HyperlinkBase") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseTitle() As Boolean
            Get
                Return CType(Me("UseTitle"), Boolean)
            End Get
            Set
                Me("UseTitle") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseSubject() As Boolean
            Get
                Return CType(Me("UseSubject"), Boolean)
            End Get
            Set
                Me("UseSubject") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseAuthor() As Boolean
            Get
                Return CType(Me("UseAuthor"), Boolean)
            End Get
            Set
                Me("UseAuthor") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseManager() As Boolean
            Get
                Return CType(Me("UseManager"), Boolean)
            End Get
            Set
                Me("UseManager") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseCompany() As Boolean
            Get
                Return CType(Me("UseCompany"), Boolean)
            End Get
            Set
                Me("UseCompany") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseCategory() As Boolean
            Get
                Return CType(Me("UseCategory"), Boolean)
            End Get
            Set
                Me("UseCategory") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseKeywords() As Boolean
            Get
                Return CType(Me("UseKeywords"), Boolean)
            End Get
            Set
                Me("UseKeywords") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseComments() As Boolean
            Get
                Return CType(Me("UseComments"), Boolean)
            End Get
            Set
                Me("UseComments") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseHyperlinkBase() As Boolean
            Get
                Return CType(Me("UseHyperlinkBase"), Boolean)
            End Get
            Set
                Me("UseHyperlinkBase") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property Location() As Point
            Get
                Return CType(Me("Location"), Point)
            End Get
            Set
                Me("Location") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property LookInSubfolders() As Boolean
            Get
                Return CType(Me("LookInSubfolders"), Boolean)
            End Get
            Set
                Me("LookInSubfolders") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property UseDocName() As Boolean
            Get
                Return CType(Me("UseDocName"), Boolean)
            End Get
            Set
                Me("UseDocName") = Value
            End Set
        End Property

        <UserScopedSetting(),
         DebuggerNonUserCode()>
        Public Property Size() As Size
            Get
                Return CType(Me("Size"), Size)
            End Get
            Set
                Me("Size") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My

    <HideModuleName(),
     DebuggerNonUserCode(),
     CompilerGenerated()>
    Friend Module MySettingsProperty

        <HelpKeyword("My.Settings")>
        Friend ReadOnly Property Settings() As MySettings
            Get
                Return MySettings.Default
            End Get
        End Property
    End Module
End Namespace
